# Generated by Django 5.1.4 on 2025-01-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfull_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
